### ISSUE TITLE
Add recommendations to the Recommendations chapter (7.2.6)

### ISSUE THREAD

**Issue by LudwigFriedmann** [asam-ev/OpenMATERIAL#130]
**Is your feature request related to a problem? Please describe.**
No recommendations are defined yet. Examples could be derived from the Miro Board.

**Describe the solution you'd like**
Add recommendations to this chapter.

**Describe alternatives you've considered**
Don't state any recommendations.

**Additional context**
-

**Comment by LudwigFriedmann** [comment]
The current list of recommendations is pretty short and doesn't provide a "full picture".
We should check the Miro Board for recommendations once again and potentially include other sources (e.g. https://resources.turbosquid.com/checkmate/checkmate-specifications/checkmate-pro-specification/) with general recommendations (e.g. "no holes within meshes").
If we manage to create a list of 10-20 recommendations we could think about keeping this chapter.
Otherwise we should postpone this topic.
After all, it should be discussed if the created list comprises non-normative recommendations or normative requirements.

**Comment by ipg-sig** [comment]
I think we don´t have to reinvent the wheel here. Maybe we can state that there are a lot of guides available for 3D model creation and optimization for specific needs (realtime, simulation ready, etc.).

Maybe it would be enough to write a few sentences and list a few examples?

Examples:
https://docs.omniverse.nvidia.com/simready/latest/simready-asset-creation.html

Otherwise and common:

- Clean geometry (no N-Gons, double vertecies/edges/faces, no loose vertecies/edges/faces, etc.)
- Polycount as high as needed and as low as possible
- No holes or gaps in the mesh
- Keep the texel density as homogeneous as possible between different assets
- Keep the texture size as low as possible (don´t use 4k textures if 1k is sufficient)
- All face normals are set correctly
- Hard and Soft Edges are set correctly
- Clean edgeflow
- Single models or the root node should have 0 Transformation (Location: 0 0 0, Rotation: 0 0 0, Scale: 1 1 1)
- All meshes/materials/nodes should be named meaningful
- UV in the 0 to 1 space
- Pay attention to texture or UV stretching
- etc

**Comment by LudwigFriedmann** [comment]
@ipg-sig : Thanks a lot, I think all of the recommendations would perfectly match that chapter! I'd start a PR and ask you for feedback.

**Comment by ipg-sig** [comment]
@MatthiasThDs To keep it short with what I mean with a "clean edgeflow": The topology corresponds to the need of the meshes, the face sides are as equal as possible and the vertecies along a edge don´t jitter, if you follow the flow of it.  But what is best or good, always depends on the asset and its purpose :) 
The quickest example I could find: http://wiki.polycount.com/wiki/File:Spheretopo_polycounts.png
The two left spheres have a "clean edgeflow", but depending on your needs you would use one or the other.
