### ISSUE TITLE
Required fields in the material schema

### ISSUE THREAD

**Issue by lyndyRott** [asam-ev/OpenMATERIAL#143]
#### Problem description
In the current version of the material schema, practically all fields are required. I could not find any materials properties which are marked optional. 

see https://github.com/asam-ev/OpenMATERIAL/blob/main/schemas/material_schema.json 

#### Question
My question is therefore: do we require anyone who contributes a material definition to know all the materials parameters for a sample that should be included?

#### Additional context
We had a discussion in the last meeting, that it is essential for the user/simulation engineer to be able to have a full set of properties of a material. 

However, from a database perspective, often not all parameters of a material have been measured or are known. 
In particular the elasticity or deformation properties might not be known for a database of reflection measurement samples. Another example are surface roughness, which is a parameter that applies across multiple scales but is often hard to measure with precision. 

#### Issue
I think it might be hard to add new material definitions in this standard if all parameters are required and need to be known. This could hinder a class of users (who are only interested in specific properties) to apply the standard in their implementations.

**Comment by Norihito-Hiruma** [comment]
I had the exact same question as Rott-san. 
Since our purpose is sensor simulation, we don't need to store all physical parameters. 
It is sufficient to store only the parameters necessary for the targeted sensor simulation. 
In order to achieve that, we primarily indicate the type of sensor being simulated in the metadata, and only store the physical quantities required for that specific sensor simulation.
As a result, many parameters, apart from a few common ones, would become optional.

**Comment by ClemensLinnhoff** [comment]
Proposal: Let's wait a couple of weeks, until we have defined all properties for version 1.0. Then let's go over all individual properties (and metadata) and decide in the group which ones are mandatory.

**Comment by ClemensLinnhoff** [comment]
To Change:

Material Schema:

metadata: required
  description: optional
  creationDate: optional
materialProperties: required
  surfaceRoughness: optional
  emissivityData: optional
  elasticityData: optional
  density: optional
  retroreflectivityData
    coefficientOfRetroreflection: Required
  electromagneticPropertiesUri: optional  


EMP Schema:
  electromagneticProperties: required
  
Optical Schema:
  opticalProperties: required

BRDF Schema:
  Remove typicalSensor to typicalSensorTechnology
  Move typicalSensorTechnology to metadata
  Change wavelengthRange to wavelengths and instead of putting min and max value in it list all contained wavelengths
