### ISSUE TITLE
Revisit amplitudeUnit in BRDF definition

### ISSUE THREAD

**Issue by ClemensLinnhoff** [asam-ev/OpenMATERIAL#167]
#### Describe the problem
Currently we have the field "amplitudeUnit" that can either be "1/sr" or "linear".
1/sr is the standard unit for BRDFs.
According to the proposal linear would be mainly used for radar. But we have not defined yet, what linear really means. 

#### Describe your research
A BRDF describes the ratio of reflected radiance along a certain angle to the irradiance incident on the surface from a certain direction.
So the BRDF values are always per angle.
From my research the unit of a BRDF (regardless of wavelength) is therefore always 1/sr.

#### Ask your question
Do we really need the amplitudeUnit parameter? And if yes, how exactly is the linear scaling defined?

@Norihito-Hiruma, @KimuraDIVP could you comment on this?

**Comment by ClemensLinnhoff** [comment]
See also the [comment](https://github.com/asam-ev/OpenMATERIAL/issues/50#issuecomment-2406445421) by @kuroda-kait that still needs to be discussed:

> At the meeting on Oct.9, topic of BRDF lookup table, there was a question regarding amplitude unit of materials.
Currently, camera and lidar uses amplitude unit of “1/sr” and radar uses “linear”, can these be unified?
DIVP thinks it is very difficult.
The “linear” value for radar amplitude means reflectance of material.
For radar, similar value of BRDF[1/sr] might be RCS[dBsm].
In “RCS” measurements, geometry of objects should be considered, but geometry is not included in a lookup table of material.
For BRDF lookup table, it is better to have amplitude unit of “1/sr” and “linear” depending on sensor types.

**Comment by Norihito-Hiruma** [comment]
We are currently discussing the content of the explanation with Mr. Kuroda from DIVP.  
Please wait a moment until Mr. Kuroda provides his response.

**Comment by kuroda-kait** [comment]
The "linear" value indicates "amplitude ratio" between an incident electric field and the reflected electric field of the material.
DIVP uses linear value from 0 to 1  ("0" means no reflection, "1" means 100% reflection) for radar.

**Comment by ClemensLinnhoff** [comment]
But isn't that the same as 1/sr?

**Comment by ClemensLinnhoff** [comment]
Let's come back to this next week to check if the linear definition of the radar BRDF is a common definition for radar simulation.

**Comment by TimoHinsemann** [comment]
Okay, thank you very much for sharing, and also for the source! Now things got more clear, so Reflectance is the quantity that can be calculated using the Fresnel equations, which makes it a "part" of the BRDF. If someone knows about the refractive indices (which are going to be stored in OpenMaterial, or at least indirectly stored with permeability and/or permittivity), he/she can use them to calculate the reflectance, but also the BRDF. So as I see it, everyone should be satisfied with the refractive indices and/or permeability & permittivity, and from a parameter standpoint, the reflectance itself is therefore redundant. Also I would probably prefer to not include it in the BRDF-Look-Up-Table, because it is a different parameter than the BRDF. But we should definitely discuss that on wednesday - maybe the electromagnetic parameters are "enough" for all of us in the end. I am looking forward to your opinions

**Comment by kuroda-kait** [comment]
Timo-san, Thank you for the comment.
Having look-up-table and parameters (the refractive indices and/or permeability & permittivity) will make some redundancy, but we think some reflections are difficult to calculate only from parameters. 
The measurement data of reflectance can include all kinds of reflection (specular reflection, retroreflection and diffuse reflection) of materials. And that is the merit to have look-up-table of reflectance.

Regarding types of look-up-tables, we agree that reflectance is different parameters than BRDF. 
So, we propose following types of look-up-table.

Conventional）
BRDF-Look-Up-Table
     - BRDF Table
     -   Radar Reflectance Table

Proposal）
Look-Up-Table
    - BRDF
    - Radar Reflectance

**Comment by ClemensLinnhoff** [comment]
Reflectance mainly used for radar, but is a different definition from a BRDF. Therefore, reflectance should be a separate look-up table.

**Comment by DavidJRitter904** [comment]
Reflectance is not only used by Radar but also for Lidar and our TOF camera!

Our material dataset provides the reflectance values of materials with respect to Lambertian Targets (ideal diffuse targets) for an angle range of 0° to 90° in 10° steps (0° incidence angle = perpendicular to material sample plane). Therefore, our unit for reflectance is given in % to the Lambertian target. 

 $$R_{λ,θ} = \frac{ I_{λ,θ} } { I_{L,λ,θ=0°} } ∗ R_{L,λ}$$

$R_{L,λ}$: reflectance of Lambertian Target given in %
$I_{λ,θ}$: measured intensity signal
$I_{L,λ,θ=0°}$: measured intensity signal of Lambertian Target in nadir / perpendicular incidence ($\theta = 0°$)

Note that values above 100% are possible, since some materials (e.g., retroreflectors) concentrate the reflected radiance back towards the illumination source. This results from the comparison to the Lambertian Target.

Providing reflectance values is a very common way for providing measured values. We know that also the sensor vendor RIEGL indicates the reflectance values with the small difference that they use dB as their unit.

Therefore, we propose to include a reflectance look-up table to fit measured reflectance values.

**Comment by kuroda-kait** [comment]
The “reflectance values” with respect to "Lambertian targets" might be a kind of relative BRDF values. 
If BRDF of ideal Lambertian targets, which is 1/π, is multiplied to above “reflectance values”, that will make BRDF[1/sr] of materials.
I think this “reflectance values” is different kind of parameters than used in radar reflectance look-up-table.

**Comment by lyndyRott** [comment]
> The “reflectance values” with respect to "Lambertian targets" might be a kind of relative BRDF values. If BRDF of ideal Lambertian targets, which is 1/π, is multiplied to above “reflectance values”, that will make BRDF[1/sr] of materials. I think this “reflectance values” is different kind of parameters than those used in radar reflectance look-up-table.

I agree with Kuroda-san. I think a relative value (**percentage** or **dB**, maybe the option to choose between the two of them) is ideal for reflectance values, not only for Radar but also for BRDFs in Lidar technology. While the typical BRDF unit **1/sr** can be calculated easily from reflectance measurements by dividing through π.
![MicrosoftTeams-image (35)](https://github.com/user-attachments/assets/09145112-2a17-4d2c-8f54-2fe6fe9bfe68)

We also want to include our database measurements in the form of a lookup-table. 

Another improvement that is needed from our point of view is to put the **wavelength** either as a general/header-parameter of the lookup-table, or in the **first column**, because it is the value of reference for looking up any BRDF.

**Comment by TimoHinsemann** [comment]
Very interesting, I also am not familiar with the "reflectance values" from above. I would agree with Kuroda-san, as it seems to be "half" a BRDF. If I see this right, the division by pi is missing, but also the division by the cosine of the exit angle is missing in order to get a BRDF. The measured intensity signal (of the probe) should be divided by the intensity signals of the Lambertian Target, that vary for different exit angles. So either measuring these "varying" Lambertian signals (and using them in the denominator), or calculating them by multiplying the measured value for 0° incidence with the cosine of the exit angle (and using this in the denominator). Anyways we should discuss tomorrow, how to handle this (possibly) additional reflectance-type, also maybe I oversee something here.

**Comment by kuroda-kait** [comment]
Lyndy-san, Timo-san, thank you for your comments. Let’s discuss this issue in the meeting.

Back to the radar look-up-table, polarization was a topic at the meeting on Nove. 13. I will try to describe in detail. 
In radar measurements, usually, the same polarization of incident and reflected electric field is measured (Incident TE – Reflected TE,  Incident TM – Reflected TM). Other combinations of polarization are negligibly small (Incident TE – Reflected TM, Incident TM – Reflected TE), then those are not included in the radar look-up-table.
A sample look-up-table, which DIVP is using, is introduced in the issue #50 and #126.
In the issue #50, three types of measurement data forms (LookupTable)  are shown, and the No.3 form can cover polarization (Incident TE – Reflected TM, Incident TM – Reflected TE). In this form No.3, the symbol θ indicates TM and symbol φ indicates TE.
https://github.com/asam-ev/OpenMATERIAL/issues/50#issuecomment-2314353360

Amplitude is the ratio of incident TE (orTM) and reflected TE (orTM). (=abs(Eref/Ein))
Phase is the angle of incident TE (orTM) and reflected TE (orTM). (=phase(Eref/Ein)).
Please refer to the following figures.
![image](https://github.com/user-attachments/assets/705f770b-39fd-40d8-93f6-1f19f400b16c)

**Comment by ClemensLinnhoff** [comment]
@kuroda-kait will prepare the schema implementation of the reflectance

**Comment by lyndyRott** [comment]
Here is the document by sensor manufacturer Riegl (Lidar sensors) 
[RIEGL_VZ-400_News_03-2009.pdf](https://github.com/user-attachments/files/17830988/RIEGL_VZ-400_News_03-2009.pdf)

see page 3 for units (dB) and the estimation of material reflectivity in %.

**Comment by ClemensLinnhoff** [comment]
@lbennes-ansys what do you think about adding a reflectivity look-up table (mainly for lidar). So having reflectivity values relative to a lambertian target.

**Comment by lyndyRott** [comment]
Some notes from our last discussion: 

Lidar **reflectivity provided in %** w.r.t. a **Lambertian** material/reflecting target (= ideal diffusely reflecting surface, radiosity is constant over all angles):
- For Lidar, typically a hemispheric reflectance (integral over half-space), also called albedo, is used to compare material properties
- 100% ... all light is reflected back into the half-space (sr = pi), no absorption or transmission
-  \>100% ... all light is reflected back, as above, however inside a cone < pi (sr), thus, the reflection is directional and the intensity is higher compared to the 100% Lambertian target
- note: reflectivity and reflectance are equal for half-space materials (not valid for thin layers or transmissive materials)
- angle-dependent reflectivity, also for Lambertian materials... according to cosine-law ( $$\rho(\phi) = \rho(0°) * cos(\phi)$$ )

Question to our colleagues with Radar expertise: 
- when comparing above procedure for Lidar reflectivity with Radar measurements, are there similarities, or are the approaches completely different?

**Comment by kuroda-kait** [comment]
I think what kind of material is used for the reference is different in Lidar reflectivity and Radar reflectance measurements.
As lyndyRott-san wrote, Lidar reflectivity is referenced to a Lambertian material (ideal diffusely reflecting surface).
For radar, reflectance is referenced to a “known specular material” (ideal specular reflecting surface), which is usually a kind of metal.
For camera/lidar, the “Super mirror” might be a similar specular material.
In radar wavelengths, which is order of millimeters, it is very hard to find a Lambertian material in reality.

**Comment by lyndyRott** [comment]
Thank you, Kuroda-san, for providing insights! 
We discussed this internally and came to the conclusion that it might be possible to use your new reflectance table for lidar reflectivities as well; At least for the time being to define this version of the standard. 
We can try to create an example, as soon as your schema is ready, and add a sensor-type key to it, to categorize it as a lidar measurement type with a % unit, for example.
Let's revisit this in our next meeting.

**Comment by Nicolas-Beaugerard** [comment]
@ClemensLinnhoff My 2 cents on this topic is that we should stick as much as possible to what the literature is providing: 1/sr for BRDF in this case. I agree with you and Mr Kuroda. This apply to electro magnetic range from visible to MWIR range. Not Thermal and millimeter waves.
 
Indeed we are not users of laser scanners where you need to roughly calibrate the sensor versus a specific target (in situ) in order to retrieve an estimative value of the reflected power. This is how users will use the device.
On our case we are creating a material description that will be used in a sensor solver that will, in the end, replicate the behavior of the real sensor. That means that our users, in the large majority of the case, won't have the material in front of them. Thus the workflow is to search in the literature the reflectivity description of the material that is the closest to the one you want for the asset. Where BRDF is really common and widely used.
 
For the Radar topic, we use the dielectric properties in conjunction with the roughness that is already provided in another schema. I discussed with my coleagues about having a lookup table that describes the reflected electric field versus the incident angle, this could work as well if we have the roughness.
Then, the 3rd table that describes the lookup table ([here](https://github.com/asam-ev/OpenMATERIAL/issues/50#issuecomment-2314353360)) could be sufficient for us.

**Comment by kuroda-kait** [comment]
Proposed Look-Up-Table
  -BRDF (Camera , Lidar )
  -Radar Reflectance

Regarding look-up-table for lidar, Japan team had internal discussion. We propose to use BRDF look-up-table for lidar.
The BRDF is well defined and widely used. Even though it would take some effort, measured lidar reflectivity data can be converted to BRDF. 
Also, from the viewpoint of standardization, increasing types of look-up-table along with types of sensors is not preferable.

**Comment by lyndyRott** [comment]
> Proposed Look-Up-Table -BRDF (Camera , Lidar ) -Radar Reflectance
> 
> Regarding look-up-table for lidar, Japan team had internal discussion. We propose to use BRDF look-up-table for lidar. The BRDF is well defined and widely used. Even though it would take some effort, measured lidar reflectivity data can be converted to BRDF. Also, from the viewpoint of standardization, increasing types of look-up-table along with types of sensors is not preferable.

@kuroda-kait 
Could you provide some derivation on the conversion of reflectivities (in %) to BRDF values for Lidar measurements? From my literature sources I was only able to find derivations which are valid for Lambertian type surfaces, thus, for perfectly-diffuse reflection.
e.g. (C 4) taken from https://www.govinfo.gov/content/pkg/GOVPUB-C13-80bc81d1913dfe186083080cbdc8ae75/pdf/GOVPUB-C13-80bc81d1913dfe186083080cbdc8ae75.pdf 
![image](https://github.com/user-attachments/assets/04c572a5-6e07-41d8-b539-c8539b09bbb8)


For ideal-specular (mirror type) surfaces I found a good conversion, however,
see (C 12) of same source 
![image](https://github.com/user-attachments/assets/e205f103-61cd-450f-b8ec-fc08d5967a69)

due to the applicability of the Dirac-delta function for perfect mirror-like reflections in (C 10) which eliminates the integration over a solid angle to a single point value. 

As you mentioned earlier (above) this assumption is valid for Radar measurements, since they are based on ideal-mirror like reference targets, if I recall correctly.

**Comment by lyndyRott** [comment]
Here are additional sources I found on the topic that could be of interest:
- on the topic of data-driven BRDF generation from measurements: (the paper describing the MERL BRDF database)
https://www.merl.com/publications/docs/TR2003-83.pdf 

- and a general overview of BRDF generation techniques
https://digibug.ugr.es/bitstream/handle/10481/19751/rmontes_LSI-2012-001TR.pdf

**Comment by kuroda-kait** [comment]
@lyndyRott 
Sorry for late response. It took time for internal discussion.
From another source(ref 1), I also found the relationship between BRDF and reflectance coefficient _ρ_  as (eq 1).
(eq 1)
![image](https://github.com/user-attachments/assets/4f7a83db-3fb6-4fca-9cc1-2f451610d217)
(ref 1)
https://www.oceanopticsbook.info/view/surfaces/lambertian-brdfs

If the reflectance _R_ [%] is defined as (eq 2), BRDF for measured sample can be calculated as (eq 3), and unit is [1/sr]. 
(eq 2)
![image](https://github.com/user-attachments/assets/53c2d546-8c52-4e1a-bae6-74e1af257e49)
(eq 3)
![image](https://github.com/user-attachments/assets/01b37e3a-ba2d-4ec2-bcc2-dd8050ed924f)

Regarding lidar, when using measured intensity signal of lidar, we have to be careful about the characteristic of intensity signal. 
Usually, there is no guarantee whether intensity signal is linear to power (=reflectivity).

**Comment by lyndyRott** [comment]
@kuroda-kait 
thank you for investigating and discussing the topic internally, and providing your approach! This is very helpful! 

We are also using the online book https://www.oceanopticsbook.info as a literature source. 

Meanwhile we came to the conclusion that when measuring the **reflectance factor** (surface reflectance over lambertian ideal ($\rho$ = 1) surface reflectance) , see https://oceanopticsbook.info/view/remote-sensing/measures-of-reflectance ,
![image](https://github.com/user-attachments/assets/edbb2b47-9823-4f81-8d2e-fa0633518004)
we are able to convert the measurements to BRDF values via dividing by $\pi$.

In https://www.oceanopticsbook.info/view/surfaces/the-brdf a nice collection and comparison of BRDFs can be found used in different domains, which can differ from one another, e.g., BRDFs in radiative transfer theory (our definition I assume) vs BRDFs in Monte Carlo (ray tracing) simulations, where they correspond to probability distribution functions (see https://www.oceanopticsbook.info/view/monte-carlo-simulation/level-2/the-brdf-as-pdf). 
We might want to clarify our definition used in the standard.

Unfortunately, also the definitions of reflectance differ with respect to different research fields
![image](https://github.com/user-attachments/assets/a8c5f5b7-55e2-4838-b7d7-92cbfeec1a61)
(taken from https://oceanopticsbook.info/view/inherent-and-apparent-optical-properties/apparent-optical-properties). 

Another point that needs to be considered is the fact that measured reflectance/reflectivity tables might be sparse compared to full BRDF functions, as expected from a computer graphics standpoint or an application engineer. 

We already discussed this with Clemens and Timo.
