### ISSUE TITLE
OpenMATERIAL Standard name and subparts

### ISSUE THREAD

**Issue by asadekasam** [asam-ev/OpenMATERIAL#169]
#### Describe the problem
The discussion is ongoing about OpenMATERIAL standard name and subparts. The purpose of this Issue is to collect the feedback from both groups on this topic, and come up with a decision or some questions to vote on.

#### Ask your question
Should we keep the name OpenMATERIAL? What other suggestions could be more suitable?

Could the Material and Geometry parts be published as subparts and companies could adhere to a specific subpart independently?

**Comment by ClemensLinnhoff** [comment]
Check proposed main introduction for the standard documentation: https://github.com/asam-ev/OpenMATERIAL/pull/166

**Comment by asadekasam** [comment]
@ClemensLinnhoff Sorry wrote that in a hurry. Question fixed now 👍

**Comment by ClemensLinnhoff** [comment]
Suggestions:

- Generally a shorter name would be prefered. We could officially name the standard "**ASAM OpenMATERIAL & 3D model structure**" but everybody would just call it "OpenMATERIAL" as a nickname.
- Technically, something like **OpenASSET** or **Open3DASSET** would be more correct, because asset refers to the entire 3D model including its materials. And this definition would enable future additions, like animations etc.
- A workaround could be naming it **OpenMATERIAL+**, **OpenMATERIALx** or **OpenMATERIAL3D** to make clear that there is more to the standard than "just" materials.
- We could have a shorter name that still facilitates both parts, e.g. **OpenMATERIAL-ASSET**, **OpenMATERIAL-GEOMETRY**
- We could just stick with **OpenMATERIAL** and people will learn over time that it also contains geometry.

**Comment by LudwigFriedmann** [comment]
The more I read it, the more I like OpenMATERIAL3D. Would it be possible to introduce a blank, i.e. **ASAM OpenMATERIAL 3D**?
Like this, the standalone expression _OpenMATERIAL_ would still be a valid reference.
Nevertheless, it would be clear that there's more to the standard than materials.

**Comment by ClemensLinnhoff** [comment]
So, with the trademark considerations we have the following options:
- ASAM OpenMATERIAL®
- ASAM OpenMATERIAL® & 3D model structure
- ASAM OpenMATERIAL® +, ASAM OpenMATERIAL® X or ASAM OpenMATERIAL® 3D
- ASAM OpenMATERIAL® Asset or ASAM OpenMATERIAL® Geometry

**Comment by MatthiasThDs** [comment]
I like
- ASAM OpenMATERIAL® 3D

**Comment by rFproMattDaley** [comment]
I would prefer:
ASAM OpenMATERIAL® Asset 
--> as asset encompasses everything about the objects... the geometry and the materials
I am building a asset for simulation and it's an ASAM OpenMATERIAL Asset
:)

**Comment by AsamDiegoSanchez** [comment]
Vote form has been created to collect responses.
Here everyone can cast their vote: https://forms.office.com/e/HhWGYz5B88

**Comment by PeteBaker1** [comment]
Is it too late to split the geometry and material sub-groups into 2 standards, as I feel like ASAM OpenGeometry and ASAM OpenMaterial is a lot more clear than having one standard with either of the above voting options.

**Comment by AsamDiegoSanchez** [comment]
As mentioned in the meetings, if we want to make it possible to reference the "Material" and the "Geometry" part independently, we have to follow the Editorial Guide Rule ASM-138 (https://internal.pages.asam.net/asam-editorial-guide/editorial-guide-generator/editorialguide-asciidoc/1.0.0/Editorial_guide/01_basics.html#sec-ASM-138).

It has to be in one standard (see example Code 2) but with separate modules, similar to OpenDRIVE:

![image](https://github.com/user-attachments/assets/287612ff-8c21-449b-8ab0-19b5a8555f45)

In our case, it could be:
ASAM OpenMATERIAL® 1.0.0
- Part 1: Core
- Part 2: Material
- Part 3: Geometry

Which means that we have to extract the chapter 7 and 8 and place them at the same level of the "core" or general information. @FKlopfer could you please check the complexity of doing this?

**Comment by martinfiebig** [comment]
Hi all, we had a look at the OpenDRIVE solution and the Antora mechanisms and found the following:
To get the solution used by OpenDRIVE, the content needs to be restructured into different 'components'. The 'module' mechanism provided by Antora is only used to organize input files and is not sufficiently displayed in the output: See [antora documentation](https://docs.antora.org/antora/latest/module-directories/#module)
Regarding the complexity, splitting the content into different 'components' is of course possible, but requires a lot of manual work - the biggest factors being the need to adapt the antora.yml configuration files, restructure the content (including nav-files and image-links throughout the content) and adapting the scripts for schema generation.

**Comment by ClemensLinnhoff** [comment]
But do we really need all that?
@AsamDiegoSanchez having two chapters, as we do now is not enough for the separation?

**Comment by AsamDiegoSanchez** [comment]
I´ve been thinking about it, there might be an option to keep the current structure just with small adjustments.
We can keep the structure but we will have to explain how the Use Cases chapter is compliant with the Geometry and Material chapters independently, because we have uses cases that are specifically for Material but not for Geometry.

The way I see it we can do it in 2 ways:
- We can take the chapter Use Cases and integrate it in the respective Geometry and Material chapters, just the uses cases that are relevant.
- We can leave the Use Cases chapter but then we have to write in the Geometry and Material chapters which uses cases are relevant.

Moreover we will have to explain better (i.e. introduction) that users can be conformed with the whole standard, or just the "Geometry" or "Material" chapters.

**Comment by ClemensLinnhoff** [comment]
We already have a use-case subchapter in the introduction of the material and geometry chapters. So splitting the use-cases would not be a problem.
And we could add one or two more sentences to [this section](https://asam-ev.github.io/OpenMATERIAL/asamopenmaterial/latest/specification/general-docs/introduction.html#_the_two_parts_of_asam_openmaterial) in the general introduction.

**Comment by AsamDiegoSanchez** [comment]
Geometry subgroup agreed with the decision from Material subgroup (see above).
